//! Protobuf types for the Substreams Bitcoin block model.
//!
//! Generated by `buf generate`; see `buf.gen.yaml`.

pub mod sf {
    pub mod bitcoin {
        pub mod r#type {
            pub mod v1 {
                include!("sf.bitcoin.type.v1.mod.rs");
            }
        }
    }
}

/// Re-export under a shorter path; `pb::btc::v1` predates `pb::sf::bitcoin::type::v1`
/// and is what downstream modules import.
pub mod btc {
    pub mod v1 {
        pub use crate::pb::sf::bitcoin::r#type::v1::*;
    }
}
