// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/bitcoin/type/v1/type.proto

#[derive(Clone, PartialEq, Default)]
pub struct Block {
    /// the block hash
    /// Bitcoin core reverses the byte order of the hash when printing it out has Hex, to prevent
    /// the end user from making a mistake we store it as a string directly
    ///
    /// Field 1: `hash`
    pub hash: ::buffa::alloc::string::String,
    /// NON-DETERMINISTIC: The number of confirmations, or -1 if the block is not on the main chain
    /// int64 confirmations = 2;
    /// it will be read and reflected indirectly inside the pbbstream.block's LIB
    ///
    /// The block size
    ///
    /// Field 3: `size`
    pub size: i32,
    /// The block size excluding witness data
    ///
    /// Field 4: `stripped_size`
    pub stripped_size: i32,
    /// The block weight as defined in BIP 141
    ///
    /// Field 5: `weight`
    pub weight: i32,
    /// The block height or index
    ///
    /// Field 6: `height`
    pub height: i64,
    /// The block version
    ///
    /// Field 7: `version`
    pub version: i32,
    /// The block version formatted in hexadecimal
    ///
    /// Field 8: `version_hex`
    pub version_hex: ::buffa::alloc::string::String,
    /// The merkle root
    ///
    /// Field 9: `merkle_root`
    pub merkle_root: ::buffa::alloc::string::String,
    /// Transaction array
    ///
    /// Field 10: `tx`
    pub tx: ::buffa::alloc::vec::Vec<Transaction>,
    /// The block time expressed in UNIX epoch time
    ///
    /// Field 11: `time`
    pub time: i64,
    /// The median block time expressed in UNIX epoch time
    ///
    /// Field 12: `mediantime`
    pub mediantime: i64,
    /// The nonce
    ///
    /// Field 13: `nonce`
    pub nonce: u32,
    /// The bits
    ///
    /// Field 14: `bits`
    pub bits: ::buffa::alloc::string::String,
    /// The difficulty
    ///
    /// Field 15: `difficulty`
    pub difficulty: f64,
    /// Expected number of hashes required to produce the chain up to this block (in hex)
    ///
    /// Field 16: `chainwork`
    pub chainwork: ::buffa::alloc::string::String,
    /// The number of transactions in the block
    ///
    /// Field 17: `n_tx`
    pub n_tx: u32,
    /// The hash of the previous block
    ///
    /// Field 18: `previous_hash`
    pub previous_hash: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for Block {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Block")
            .field("hash", &self.hash)
            .field("size", &self.size)
            .field("stripped_size", &self.stripped_size)
            .field("weight", &self.weight)
            .field("height", &self.height)
            .field("version", &self.version)
            .field("version_hex", &self.version_hex)
            .field("merkle_root", &self.merkle_root)
            .field("tx", &self.tx)
            .field("time", &self.time)
            .field("mediantime", &self.mediantime)
            .field("nonce", &self.nonce)
            .field("bits", &self.bits)
            .field("difficulty", &self.difficulty)
            .field("chainwork", &self.chainwork)
            .field("n_tx", &self.n_tx)
            .field("previous_hash", &self.previous_hash)
            .finish()
    }
}
impl Block {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Block";
}
::buffa::impl_default_instance!(Block);
impl ::buffa::MessageName for Block {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Block";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Block";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Block";
}
impl ::buffa::Message for Block {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hash) as u64;
        }
        if self.size != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.size) as u64;
        }
        if self.stripped_size != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.stripped_size) as u64;
        }
        if self.weight != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.weight) as u64;
        }
        if self.height != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.height) as u64;
        }
        if self.version != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.version) as u64;
        }
        if !self.version_hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.version_hex) as u64;
        }
        if !self.merkle_root.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.merkle_root) as u64;
        }
        for v in &self.tx {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.time != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.time) as u64;
        }
        if self.mediantime != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.mediantime) as u64;
        }
        if self.nonce != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.nonce) as u64;
        }
        if !self.bits.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.bits) as u64;
        }
        if self.difficulty.to_bits() != 0u64 {
            size += 1u64 + ::buffa::types::FIXED64_ENCODED_LEN as u64;
        }
        if !self.chainwork.is_empty() {
            size += 2u64 + ::buffa::types::string_encoded_len(&self.chainwork) as u64;
        }
        if self.n_tx != 0u32 {
            size += 2u64 + ::buffa::types::uint32_encoded_len(self.n_tx) as u64;
        }
        if !self.previous_hash.is_empty() {
            size
                += 2u64 + ::buffa::types::string_encoded_len(&self.previous_hash) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.hash.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.hash, buf);
        }
        if self.size != 0i32 {
            ::buffa::types::put_int32_field(3u32, self.size, buf);
        }
        if self.stripped_size != 0i32 {
            ::buffa::types::put_int32_field(4u32, self.stripped_size, buf);
        }
        if self.weight != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.weight, buf);
        }
        if self.height != 0i64 {
            ::buffa::types::put_int64_field(6u32, self.height, buf);
        }
        if self.version != 0i32 {
            ::buffa::types::put_int32_field(7u32, self.version, buf);
        }
        if !self.version_hex.is_empty() {
            ::buffa::types::put_string_field(8u32, &self.version_hex, buf);
        }
        if !self.merkle_root.is_empty() {
            ::buffa::types::put_string_field(9u32, &self.merkle_root, buf);
        }
        for v in &self.tx {
            ::buffa::types::put_len_delimited_header(
                10u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        if self.time != 0i64 {
            ::buffa::types::put_int64_field(11u32, self.time, buf);
        }
        if self.mediantime != 0i64 {
            ::buffa::types::put_int64_field(12u32, self.mediantime, buf);
        }
        if self.nonce != 0u32 {
            ::buffa::types::put_uint32_field(13u32, self.nonce, buf);
        }
        if !self.bits.is_empty() {
            ::buffa::types::put_string_field(14u32, &self.bits, buf);
        }
        if self.difficulty.to_bits() != 0u64 {
            ::buffa::types::put_double_field(15u32, self.difficulty, buf);
        }
        if !self.chainwork.is_empty() {
            ::buffa::types::put_string_field(16u32, &self.chainwork, buf);
        }
        if self.n_tx != 0u32 {
            ::buffa::types::put_uint32_field(17u32, self.n_tx, buf);
        }
        if !self.previous_hash.is_empty() {
            ::buffa::types::put_string_field(18u32, &self.previous_hash, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.hash, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.size = ::buffa::types::decode_int32(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.stripped_size = ::buffa::types::decode_int32(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.weight = ::buffa::types::decode_int32(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.height = ::buffa::types::decode_int64(buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.version = ::buffa::types::decode_int32(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.version_hex, buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.merkle_root, buf)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.tx.push(elem);
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.time = ::buffa::types::decode_int64(buf)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.mediantime = ::buffa::types::decode_int64(buf)?;
            }
            13u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.nonce = ::buffa::types::decode_uint32(buf)?;
            }
            14u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.bits, buf)?;
            }
            15u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Fixed64,
                )?;
                self.difficulty = ::buffa::types::decode_double(buf)?;
            }
            16u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.chainwork, buf)?;
            }
            17u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.n_tx = ::buffa::types::decode_uint32(buf)?;
            }
            18u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.previous_hash, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.hash.clear();
        self.size = 0i32;
        self.stripped_size = 0i32;
        self.weight = 0i32;
        self.height = 0i64;
        self.version = 0i32;
        self.version_hex.clear();
        self.merkle_root.clear();
        self.tx.clear();
        self.time = 0i64;
        self.mediantime = 0i64;
        self.nonce = 0u32;
        self.bits.clear();
        self.difficulty = 0f64;
        self.chainwork.clear();
        self.n_tx = 0u32;
        self.previous_hash.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Transaction {
    /// The serialized, hex-encoded data for 'txid'
    ///
    /// Field 1: `hex`
    pub hex: ::buffa::alloc::string::String,
    /// The transaction id
    ///
    /// Field 2: `txid`
    pub txid: ::buffa::alloc::string::String,
    /// The transaction hash (differs from txid for witness transactions)
    ///
    /// Field 3: `hash`
    pub hash: ::buffa::alloc::string::String,
    /// The serialized transaction size
    ///
    /// Field 4: `size`
    pub size: i32,
    /// The virtual transaction size (differs from size for witness transactions)
    ///
    /// Field 5: `vsize`
    pub vsize: i32,
    /// The transaction's weight (between vsize*4-3 and vsize*4)
    ///
    /// Field 6: `weight`
    pub weight: i32,
    ///  The version
    ///
    /// Field 7: `version`
    pub version: u32,
    /// The lock time
    ///
    /// Field 8: `locktime`
    pub locktime: u32,
    /// Field 9: `vin`
    pub vin: ::buffa::alloc::vec::Vec<Vin>,
    /// Field 10: `vout`
    pub vout: ::buffa::alloc::vec::Vec<Vout>,
    /// the block hash
    ///
    /// Field 11: `blockhash`
    pub blockhash: ::buffa::alloc::string::String,
    /// The block time expressed in UNIX epoch time
    ///
    /// Field 12: `blocktime`
    pub blocktime: i64,
}
impl ::core::fmt::Debug for Transaction {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Transaction")
            .field("hex", &self.hex)
            .field("txid", &self.txid)
            .field("hash", &self.hash)
            .field("size", &self.size)
            .field("vsize", &self.vsize)
            .field("weight", &self.weight)
            .field("version", &self.version)
            .field("locktime", &self.locktime)
            .field("vin", &self.vin)
            .field("vout", &self.vout)
            .field("blockhash", &self.blockhash)
            .field("blocktime", &self.blocktime)
            .finish()
    }
}
impl Transaction {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Transaction";
}
::buffa::impl_default_instance!(Transaction);
impl ::buffa::MessageName for Transaction {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Transaction";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Transaction";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Transaction";
}
impl ::buffa::Message for Transaction {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hex) as u64;
        }
        if !self.txid.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.txid) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hash) as u64;
        }
        if self.size != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.size) as u64;
        }
        if self.vsize != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.vsize) as u64;
        }
        if self.weight != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.weight) as u64;
        }
        if self.version != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.version) as u64;
        }
        if self.locktime != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.locktime) as u64;
        }
        for v in &self.vin {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.vout {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if !self.blockhash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.blockhash) as u64;
        }
        if self.blocktime != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.blocktime) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.hex.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.hex, buf);
        }
        if !self.txid.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.txid, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.hash, buf);
        }
        if self.size != 0i32 {
            ::buffa::types::put_int32_field(4u32, self.size, buf);
        }
        if self.vsize != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.vsize, buf);
        }
        if self.weight != 0i32 {
            ::buffa::types::put_int32_field(6u32, self.weight, buf);
        }
        if self.version != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.version, buf);
        }
        if self.locktime != 0u32 {
            ::buffa::types::put_uint32_field(8u32, self.locktime, buf);
        }
        for v in &self.vin {
            ::buffa::types::put_len_delimited_header(
                9u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.vout {
            ::buffa::types::put_len_delimited_header(
                10u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        if !self.blockhash.is_empty() {
            ::buffa::types::put_string_field(11u32, &self.blockhash, buf);
        }
        if self.blocktime != 0i64 {
            ::buffa::types::put_int64_field(12u32, self.blocktime, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.hex, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.txid, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.hash, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.size = ::buffa::types::decode_int32(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.vsize = ::buffa::types::decode_int32(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.weight = ::buffa::types::decode_int32(buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.version = ::buffa::types::decode_uint32(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.locktime = ::buffa::types::decode_uint32(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.vin.push(elem);
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.vout.push(elem);
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.blockhash, buf)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.blocktime = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.hex.clear();
        self.txid.clear();
        self.hash.clear();
        self.size = 0i32;
        self.vsize = 0i32;
        self.weight = 0i32;
        self.version = 0u32;
        self.locktime = 0u32;
        self.vin.clear();
        self.vout.clear();
        self.blockhash.clear();
        self.blocktime = 0i64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Vin {
    /// The transaction id
    ///
    /// Field 1: `txid`
    pub txid: ::buffa::alloc::string::String,
    /// The output number
    ///
    /// Field 2: `vout`
    pub vout: u32,
    /// The script
    ///
    /// Field 3: `script_sig`
    pub script_sig: ::buffa::MessageField<ScriptSig, ::buffa::Inline<ScriptSig>>,
    /// The script sequence number
    ///
    /// Field 4: `sequence`
    pub sequence: u32,
    /// hex-encoded witness data (if any)
    ///
    /// Field 5: `txinwitness`
    pub txinwitness: ::buffa::alloc::vec::Vec<::buffa::alloc::string::String>,
    /// hex-encoded coinbase
    ///
    /// Field 6: `coinbase`
    pub coinbase: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for Vin {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Vin")
            .field("txid", &self.txid)
            .field("vout", &self.vout)
            .field("script_sig", &self.script_sig)
            .field("sequence", &self.sequence)
            .field("txinwitness", &self.txinwitness)
            .field("coinbase", &self.coinbase)
            .finish()
    }
}
impl Vin {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Vin";
}
::buffa::impl_default_instance!(Vin);
impl ::buffa::MessageName for Vin {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Vin";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Vin";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Vin";
}
impl ::buffa::Message for Vin {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.txid.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.txid) as u64;
        }
        if self.vout != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.vout) as u64;
        }
        if self.script_sig.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.script_sig.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.sequence != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.sequence) as u64;
        }
        for v in &self.txinwitness {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if !self.coinbase.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.coinbase) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.txid.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.txid, buf);
        }
        if self.vout != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.vout, buf);
        }
        if self.script_sig.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.script_sig.write_to(__cache, buf);
        }
        if self.sequence != 0u32 {
            ::buffa::types::put_uint32_field(4u32, self.sequence, buf);
        }
        for v in &self.txinwitness {
            ::buffa::types::put_string_field(5u32, v, buf);
        }
        if !self.coinbase.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.coinbase, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.txid, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.vout = ::buffa::types::decode_uint32(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.script_sig.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.sequence = ::buffa::types::decode_uint32(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::decode_string(buf)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                self.txinwitness.push(__elem);
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.coinbase, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.txid.clear();
        self.vout = 0u32;
        self.script_sig = ::buffa::MessageField::none();
        self.sequence = 0u32;
        self.txinwitness.clear();
        self.coinbase.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
#[allow(non_snake_case)]
pub struct Vout {
    /// The value in BTC
    ///
    /// Field 1: `value`
    pub value: f64,
    /// index
    ///
    /// Field 2: `n`
    pub n: u32,
    /// Field 3: `script_pubKey`
    pub script_pubKey: ::buffa::MessageField<
        ScriptPubKey,
        ::buffa::Inline<ScriptPubKey>,
    >,
}
impl ::core::fmt::Debug for Vout {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Vout")
            .field("value", &self.value)
            .field("n", &self.n)
            .field("script_pubKey", &self.script_pubKey)
            .finish()
    }
}
impl Vout {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Vout";
}
::buffa::impl_default_instance!(Vout);
impl ::buffa::MessageName for Vout {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Vout";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Vout";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Vout";
}
impl ::buffa::Message for Vout {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.value.to_bits() != 0u64 {
            size += 1u64 + ::buffa::types::FIXED64_ENCODED_LEN as u64;
        }
        if self.n != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.n) as u64;
        }
        if self.script_pubKey.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.script_pubKey.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.value.to_bits() != 0u64 {
            ::buffa::types::put_double_field(1u32, self.value, buf);
        }
        if self.n != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.n, buf);
        }
        if self.script_pubKey.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.script_pubKey.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Fixed64,
                )?;
                self.value = ::buffa::types::decode_double(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.n = ::buffa::types::decode_uint32(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.script_pubKey.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.value = 0f64;
        self.n = 0u32;
        self.script_pubKey = ::buffa::MessageField::none();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ScriptSig {
    /// The asm
    ///
    /// Field 1: `asm`
    pub asm: ::buffa::alloc::string::String,
    /// The hex
    ///
    /// Field 2: `hex`
    pub hex: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for ScriptSig {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ScriptSig")
            .field("asm", &self.asm)
            .field("hex", &self.hex)
            .finish()
    }
}
impl ScriptSig {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.ScriptSig";
}
::buffa::impl_default_instance!(ScriptSig);
impl ::buffa::MessageName for ScriptSig {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "ScriptSig";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.ScriptSig";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.ScriptSig";
}
impl ::buffa::Message for ScriptSig {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.asm.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.asm) as u64;
        }
        if !self.hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hex) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.asm.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.asm, buf);
        }
        if !self.hex.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.hex, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.asm, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.hex, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.asm.clear();
        self.hex.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ScriptPubKey {
    /// the asm
    ///
    /// Field 1: `asm`
    pub asm: ::buffa::alloc::string::String,
    /// the hex
    ///
    /// Field 2: `hex`
    pub hex: ::buffa::alloc::string::String,
    /// The required sigs
    ///
    /// Field 3: `req_sigs`
    pub req_sigs: i32,
    /// The type, eg 'pubkeyhash'
    ///
    /// Field 4: `type`
    pub r#type: ::buffa::alloc::string::String,
    /// bitcoin address
    ///
    /// Field 5: `address`
    pub address: ::buffa::alloc::string::String,
    /// bitcoin addresses (deprecated, empty when 'address' is set)
    ///
    /// Field 6: `addresses`
    pub addresses: ::buffa::alloc::vec::Vec<::buffa::alloc::string::String>,
}
impl ::core::fmt::Debug for ScriptPubKey {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ScriptPubKey")
            .field("asm", &self.asm)
            .field("hex", &self.hex)
            .field("req_sigs", &self.req_sigs)
            .field("type", &self.r#type)
            .field("address", &self.address)
            .field("addresses", &self.addresses)
            .finish()
    }
}
impl ScriptPubKey {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.ScriptPubKey";
}
::buffa::impl_default_instance!(ScriptPubKey);
impl ::buffa::MessageName for ScriptPubKey {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "ScriptPubKey";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.ScriptPubKey";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.ScriptPubKey";
}
impl ::buffa::Message for ScriptPubKey {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.asm.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.asm) as u64;
        }
        if !self.hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hex) as u64;
        }
        if self.req_sigs != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.req_sigs) as u64;
        }
        if !self.r#type.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.r#type) as u64;
        }
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.address) as u64;
        }
        for v in &self.addresses {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.asm.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.asm, buf);
        }
        if !self.hex.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.hex, buf);
        }
        if self.req_sigs != 0i32 {
            ::buffa::types::put_int32_field(3u32, self.req_sigs, buf);
        }
        if !self.r#type.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.r#type, buf);
        }
        if !self.address.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.address, buf);
        }
        for v in &self.addresses {
            ::buffa::types::put_string_field(6u32, v, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.asm, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.hex, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.req_sigs = ::buffa::types::decode_int32(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.r#type, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.address, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::decode_string(buf)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                self.addresses.push(__elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.asm.clear();
        self.hex.clear();
        self.req_sigs = 0i32;
        self.r#type.clear();
        self.address.clear();
        self.addresses.clear();
    }
}
