// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.bitcoin.type.v1.type.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.bitcoin.type.v1.type.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.bitcoin.type.v1.type.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::BlockView;
#[doc(inline)]
pub use self::__buffa::view::BlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionView;
#[doc(inline)]
pub use self::__buffa::view::TransactionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionLazyView;
#[doc(inline)]
pub use self::__buffa::view::VinView;
#[doc(inline)]
pub use self::__buffa::view::VinOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::VinLazyView;
#[doc(inline)]
pub use self::__buffa::view::VoutView;
#[doc(inline)]
pub use self::__buffa::view::VoutOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::VoutLazyView;
#[doc(inline)]
pub use self::__buffa::view::ScriptSigView;
#[doc(inline)]
pub use self::__buffa::view::ScriptSigOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ScriptSigLazyView;
#[doc(inline)]
pub use self::__buffa::view::ScriptPubKeyView;
#[doc(inline)]
pub use self::__buffa::view::ScriptPubKeyOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ScriptPubKeyLazyView;
