// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/bitcoin/type/v1/type.proto

#[derive(Clone, Debug, Default)]
pub struct BlockView<'a> {
    /// the block hash
    /// Bitcoin core reverses the byte order of the hash when printing it out has Hex, to prevent
    /// the end user from making a mistake we store it as a string directly
    ///
    /// Field 1: `hash`
    pub hash: &'a str,
    /// NON-DETERMINISTIC: The number of confirmations, or -1 if the block is not on the main chain
    /// int64 confirmations = 2;
    /// it will be read and reflected indirectly inside the pbbstream.block's LIB
    ///
    /// The block size
    ///
    /// Field 3: `size`
    pub size: i32,
    /// The block size excluding witness data
    ///
    /// Field 4: `stripped_size`
    pub stripped_size: i32,
    /// The block weight as defined in BIP 141
    ///
    /// Field 5: `weight`
    pub weight: i32,
    /// The block height or index
    ///
    /// Field 6: `height`
    pub height: i64,
    /// The block version
    ///
    /// Field 7: `version`
    pub version: i32,
    /// The block version formatted in hexadecimal
    ///
    /// Field 8: `version_hex`
    pub version_hex: &'a str,
    /// The merkle root
    ///
    /// Field 9: `merkle_root`
    pub merkle_root: &'a str,
    /// Transaction array
    ///
    /// Field 10: `tx`
    pub tx: ::buffa::RepeatedView<'a, super::super::__buffa::view::TransactionView<'a>>,
    /// The block time expressed in UNIX epoch time
    ///
    /// Field 11: `time`
    pub time: i64,
    /// The median block time expressed in UNIX epoch time
    ///
    /// Field 12: `mediantime`
    pub mediantime: i64,
    /// The nonce
    ///
    /// Field 13: `nonce`
    pub nonce: u32,
    /// The bits
    ///
    /// Field 14: `bits`
    pub bits: &'a str,
    /// The difficulty
    ///
    /// Field 15: `difficulty`
    pub difficulty: f64,
    /// Expected number of hashes required to produce the chain up to this block (in hex)
    ///
    /// Field 16: `chainwork`
    pub chainwork: &'a str,
    /// The number of transactions in the block
    ///
    /// Field 17: `n_tx`
    pub n_tx: u32,
    /// The hash of the previous block
    ///
    /// Field 18: `previous_hash`
    pub previous_hash: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for BlockView<'a> {
    type Owned = super::super::Block;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.size = ::buffa::types::decode_int32(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.stripped_size = ::buffa::types::decode_int32(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.weight = ::buffa::types::decode_int32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.height = ::buffa::types::decode_int64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.version = ::buffa::types::decode_int32(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.version_hex = ::buffa::types::borrow_str(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.merkle_root = ::buffa::types::borrow_str(&mut cur)?;
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.time = ::buffa::types::decode_int64(&mut cur)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.mediantime = ::buffa::types::decode_int64(&mut cur)?;
            }
            13u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.nonce = ::buffa::types::decode_uint32(&mut cur)?;
            }
            14u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.bits = ::buffa::types::borrow_str(&mut cur)?;
            }
            15u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Fixed64,
                )?;
                view.difficulty = ::buffa::types::decode_double(&mut cur)?;
            }
            16u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.chainwork = ::buffa::types::borrow_str(&mut cur)?;
            }
            17u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.n_tx = ::buffa::types::decode_uint32(&mut cur)?;
            }
            18u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.previous_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::TransactionView,
                    >(),
                )?;
                view.tx
                    .push(
                        <super::super::__buffa::view::TransactionView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Block, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Block, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Block {
            hash: self.hash.to_string(),
            size: self.size,
            stripped_size: self.stripped_size,
            weight: self.weight,
            height: self.height,
            version: self.version,
            version_hex: self.version_hex.to_string(),
            merkle_root: self.merkle_root.to_string(),
            tx: self
                .tx
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            time: self.time,
            mediantime: self.mediantime,
            nonce: self.nonce,
            bits: self.bits.to_string(),
            difficulty: self.difficulty,
            chainwork: self.chainwork.to_string(),
            n_tx: self.n_tx,
            previous_hash: self.previous_hash.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for BlockView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hash) as u64;
        }
        if self.size != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.size) as u64;
        }
        if self.stripped_size != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.stripped_size) as u64;
        }
        if self.weight != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.weight) as u64;
        }
        if self.height != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.height) as u64;
        }
        if self.version != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.version) as u64;
        }
        if !self.version_hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.version_hex) as u64;
        }
        if !self.merkle_root.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.merkle_root) as u64;
        }
        for v in &self.tx {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.time != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.time) as u64;
        }
        if self.mediantime != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.mediantime) as u64;
        }
        if self.nonce != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.nonce) as u64;
        }
        if !self.bits.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.bits) as u64;
        }
        if self.difficulty.to_bits() != 0u64 {
            size += 1u64 + ::buffa::types::FIXED64_ENCODED_LEN as u64;
        }
        if !self.chainwork.is_empty() {
            size += 2u64 + ::buffa::types::string_encoded_len(&self.chainwork) as u64;
        }
        if self.n_tx != 0u32 {
            size += 2u64 + ::buffa::types::uint32_encoded_len(self.n_tx) as u64;
        }
        if !self.previous_hash.is_empty() {
            size
                += 2u64 + ::buffa::types::string_encoded_len(&self.previous_hash) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.hash.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.hash, buf);
        }
        if self.size != 0i32 {
            ::buffa::types::put_int32_field(3u32, self.size, buf);
        }
        if self.stripped_size != 0i32 {
            ::buffa::types::put_int32_field(4u32, self.stripped_size, buf);
        }
        if self.weight != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.weight, buf);
        }
        if self.height != 0i64 {
            ::buffa::types::put_int64_field(6u32, self.height, buf);
        }
        if self.version != 0i32 {
            ::buffa::types::put_int32_field(7u32, self.version, buf);
        }
        if !self.version_hex.is_empty() {
            ::buffa::types::put_string_field(8u32, &self.version_hex, buf);
        }
        if !self.merkle_root.is_empty() {
            ::buffa::types::put_string_field(9u32, &self.merkle_root, buf);
        }
        for v in &self.tx {
            ::buffa::types::put_len_delimited_header(
                10u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        if self.time != 0i64 {
            ::buffa::types::put_int64_field(11u32, self.time, buf);
        }
        if self.mediantime != 0i64 {
            ::buffa::types::put_int64_field(12u32, self.mediantime, buf);
        }
        if self.nonce != 0u32 {
            ::buffa::types::put_uint32_field(13u32, self.nonce, buf);
        }
        if !self.bits.is_empty() {
            ::buffa::types::put_string_field(14u32, &self.bits, buf);
        }
        if self.difficulty.to_bits() != 0u64 {
            ::buffa::types::put_double_field(15u32, self.difficulty, buf);
        }
        if !self.chainwork.is_empty() {
            ::buffa::types::put_string_field(16u32, &self.chainwork, buf);
        }
        if self.n_tx != 0u32 {
            ::buffa::types::put_uint32_field(17u32, self.n_tx, buf);
        }
        if !self.previous_hash.is_empty() {
            ::buffa::types::put_string_field(18u32, &self.previous_hash, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for BlockView<'a> {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Block";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Block";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Block";
}
::buffa::impl_default_view_instance!(BlockView);
::buffa::impl_view_reborrow!(BlockView);
/** Self-contained, `'static` owned view of a `Block` message.

 Wraps [`::buffa::OwnedView`]`<`[`BlockView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`BlockView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct BlockOwnedView(::buffa::OwnedView<BlockView<'static>>);
impl BlockOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(BlockOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Block,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(BlockOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`BlockView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &BlockView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Block {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// the block hash
    /// Bitcoin core reverses the byte order of the hash when printing it out has Hex, to prevent
    /// the end user from making a mistake we store it as a string directly
    ///
    /// Field 1: `hash`
    #[must_use]
    pub fn hash(&self) -> &'_ str {
        self.0.reborrow().hash
    }
    /// NON-DETERMINISTIC: The number of confirmations, or -1 if the block is not on the main chain
    /// int64 confirmations = 2;
    /// it will be read and reflected indirectly inside the pbbstream.block's LIB
    ///
    /// The block size
    ///
    /// Field 3: `size`
    #[must_use]
    pub fn size(&self) -> i32 {
        self.0.reborrow().size
    }
    /// The block size excluding witness data
    ///
    /// Field 4: `stripped_size`
    #[must_use]
    pub fn stripped_size(&self) -> i32 {
        self.0.reborrow().stripped_size
    }
    /// The block weight as defined in BIP 141
    ///
    /// Field 5: `weight`
    #[must_use]
    pub fn weight(&self) -> i32 {
        self.0.reborrow().weight
    }
    /// The block height or index
    ///
    /// Field 6: `height`
    #[must_use]
    pub fn height(&self) -> i64 {
        self.0.reborrow().height
    }
    /// The block version
    ///
    /// Field 7: `version`
    #[must_use]
    pub fn version(&self) -> i32 {
        self.0.reborrow().version
    }
    /// The block version formatted in hexadecimal
    ///
    /// Field 8: `version_hex`
    #[must_use]
    pub fn version_hex(&self) -> &'_ str {
        self.0.reborrow().version_hex
    }
    /// The merkle root
    ///
    /// Field 9: `merkle_root`
    #[must_use]
    pub fn merkle_root(&self) -> &'_ str {
        self.0.reborrow().merkle_root
    }
    /// Transaction array
    ///
    /// Field 10: `tx`
    #[must_use]
    pub fn tx(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::TransactionView<'_>> {
        &self.0.reborrow().tx
    }
    /// The block time expressed in UNIX epoch time
    ///
    /// Field 11: `time`
    #[must_use]
    pub fn time(&self) -> i64 {
        self.0.reborrow().time
    }
    /// The median block time expressed in UNIX epoch time
    ///
    /// Field 12: `mediantime`
    #[must_use]
    pub fn mediantime(&self) -> i64 {
        self.0.reborrow().mediantime
    }
    /// The nonce
    ///
    /// Field 13: `nonce`
    #[must_use]
    pub fn nonce(&self) -> u32 {
        self.0.reborrow().nonce
    }
    /// The bits
    ///
    /// Field 14: `bits`
    #[must_use]
    pub fn bits(&self) -> &'_ str {
        self.0.reborrow().bits
    }
    /// The difficulty
    ///
    /// Field 15: `difficulty`
    #[must_use]
    pub fn difficulty(&self) -> f64 {
        self.0.reborrow().difficulty
    }
    /// Expected number of hashes required to produce the chain up to this block (in hex)
    ///
    /// Field 16: `chainwork`
    #[must_use]
    pub fn chainwork(&self) -> &'_ str {
        self.0.reborrow().chainwork
    }
    /// The number of transactions in the block
    ///
    /// Field 17: `n_tx`
    #[must_use]
    pub fn n_tx(&self) -> u32 {
        self.0.reborrow().n_tx
    }
    /// The hash of the previous block
    ///
    /// Field 18: `previous_hash`
    #[must_use]
    pub fn previous_hash(&self) -> &'_ str {
        self.0.reborrow().previous_hash
    }
}
impl ::core::convert::From<::buffa::OwnedView<BlockView<'static>>> for BlockOwnedView {
    fn from(inner: ::buffa::OwnedView<BlockView<'static>>) -> Self {
        BlockOwnedView(inner)
    }
}
impl ::core::convert::From<BlockOwnedView> for ::buffa::OwnedView<BlockView<'static>> {
    fn from(wrapper: BlockOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<BlockView<'static>>> for BlockOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<BlockView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Block {
    type View<'a> = BlockView<'a>;
    type ViewHandle = BlockOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct TransactionView<'a> {
    /// The serialized, hex-encoded data for 'txid'
    ///
    /// Field 1: `hex`
    pub hex: &'a str,
    /// The transaction id
    ///
    /// Field 2: `txid`
    pub txid: &'a str,
    /// The transaction hash (differs from txid for witness transactions)
    ///
    /// Field 3: `hash`
    pub hash: &'a str,
    /// The serialized transaction size
    ///
    /// Field 4: `size`
    pub size: i32,
    /// The virtual transaction size (differs from size for witness transactions)
    ///
    /// Field 5: `vsize`
    pub vsize: i32,
    /// The transaction's weight (between vsize*4-3 and vsize*4)
    ///
    /// Field 6: `weight`
    pub weight: i32,
    ///  The version
    ///
    /// Field 7: `version`
    pub version: u32,
    /// The lock time
    ///
    /// Field 8: `locktime`
    pub locktime: u32,
    /// Field 9: `vin`
    pub vin: ::buffa::RepeatedView<'a, super::super::__buffa::view::VinView<'a>>,
    /// Field 10: `vout`
    pub vout: ::buffa::RepeatedView<'a, super::super::__buffa::view::VoutView<'a>>,
    /// the block hash
    ///
    /// Field 11: `blockhash`
    pub blockhash: &'a str,
    /// The block time expressed in UNIX epoch time
    ///
    /// Field 12: `blocktime`
    pub blocktime: i64,
}
impl<'a> ::buffa::MessageView<'a> for TransactionView<'a> {
    type Owned = super::super::Transaction;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hex = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.txid = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.size = ::buffa::types::decode_int32(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.vsize = ::buffa::types::decode_int32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.weight = ::buffa::types::decode_int32(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.version = ::buffa::types::decode_uint32(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.locktime = ::buffa::types::decode_uint32(&mut cur)?;
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.blockhash = ::buffa::types::borrow_str(&mut cur)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.blocktime = ::buffa::types::decode_int64(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::VinView>(),
                )?;
                view.vin
                    .push(
                        <super::super::__buffa::view::VinView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::VoutView>(),
                )?;
                view.vout
                    .push(
                        <super::super::__buffa::view::VoutView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Transaction, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Transaction, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Transaction {
            hex: self.hex.to_string(),
            txid: self.txid.to_string(),
            hash: self.hash.to_string(),
            size: self.size,
            vsize: self.vsize,
            weight: self.weight,
            version: self.version,
            locktime: self.locktime,
            vin: self
                .vin
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            vout: self
                .vout
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            blockhash: self.blockhash.to_string(),
            blocktime: self.blocktime,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for TransactionView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hex) as u64;
        }
        if !self.txid.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.txid) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hash) as u64;
        }
        if self.size != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.size) as u64;
        }
        if self.vsize != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.vsize) as u64;
        }
        if self.weight != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.weight) as u64;
        }
        if self.version != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.version) as u64;
        }
        if self.locktime != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.locktime) as u64;
        }
        for v in &self.vin {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.vout {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if !self.blockhash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.blockhash) as u64;
        }
        if self.blocktime != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.blocktime) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.hex.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.hex, buf);
        }
        if !self.txid.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.txid, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.hash, buf);
        }
        if self.size != 0i32 {
            ::buffa::types::put_int32_field(4u32, self.size, buf);
        }
        if self.vsize != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.vsize, buf);
        }
        if self.weight != 0i32 {
            ::buffa::types::put_int32_field(6u32, self.weight, buf);
        }
        if self.version != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.version, buf);
        }
        if self.locktime != 0u32 {
            ::buffa::types::put_uint32_field(8u32, self.locktime, buf);
        }
        for v in &self.vin {
            ::buffa::types::put_len_delimited_header(
                9u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.vout {
            ::buffa::types::put_len_delimited_header(
                10u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        if !self.blockhash.is_empty() {
            ::buffa::types::put_string_field(11u32, &self.blockhash, buf);
        }
        if self.blocktime != 0i64 {
            ::buffa::types::put_int64_field(12u32, self.blocktime, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for TransactionView<'a> {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Transaction";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Transaction";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Transaction";
}
::buffa::impl_default_view_instance!(TransactionView);
::buffa::impl_view_reborrow!(TransactionView);
/** Self-contained, `'static` owned view of a `Transaction` message.

 Wraps [`::buffa::OwnedView`]`<`[`TransactionView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`TransactionView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct TransactionOwnedView(::buffa::OwnedView<TransactionView<'static>>);
impl TransactionOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TransactionOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TransactionOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Transaction,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TransactionOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`TransactionView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &TransactionView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Transaction {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The serialized, hex-encoded data for 'txid'
    ///
    /// Field 1: `hex`
    #[must_use]
    pub fn hex(&self) -> &'_ str {
        self.0.reborrow().hex
    }
    /// The transaction id
    ///
    /// Field 2: `txid`
    #[must_use]
    pub fn txid(&self) -> &'_ str {
        self.0.reborrow().txid
    }
    /// The transaction hash (differs from txid for witness transactions)
    ///
    /// Field 3: `hash`
    #[must_use]
    pub fn hash(&self) -> &'_ str {
        self.0.reborrow().hash
    }
    /// The serialized transaction size
    ///
    /// Field 4: `size`
    #[must_use]
    pub fn size(&self) -> i32 {
        self.0.reborrow().size
    }
    /// The virtual transaction size (differs from size for witness transactions)
    ///
    /// Field 5: `vsize`
    #[must_use]
    pub fn vsize(&self) -> i32 {
        self.0.reborrow().vsize
    }
    /// The transaction's weight (between vsize*4-3 and vsize*4)
    ///
    /// Field 6: `weight`
    #[must_use]
    pub fn weight(&self) -> i32 {
        self.0.reborrow().weight
    }
    ///  The version
    ///
    /// Field 7: `version`
    #[must_use]
    pub fn version(&self) -> u32 {
        self.0.reborrow().version
    }
    /// The lock time
    ///
    /// Field 8: `locktime`
    #[must_use]
    pub fn locktime(&self) -> u32 {
        self.0.reborrow().locktime
    }
    /// Field 9: `vin`
    #[must_use]
    pub fn vin(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::VinView<'_>> {
        &self.0.reborrow().vin
    }
    /// Field 10: `vout`
    #[must_use]
    pub fn vout(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::VoutView<'_>> {
        &self.0.reborrow().vout
    }
    /// the block hash
    ///
    /// Field 11: `blockhash`
    #[must_use]
    pub fn blockhash(&self) -> &'_ str {
        self.0.reborrow().blockhash
    }
    /// The block time expressed in UNIX epoch time
    ///
    /// Field 12: `blocktime`
    #[must_use]
    pub fn blocktime(&self) -> i64 {
        self.0.reborrow().blocktime
    }
}
impl ::core::convert::From<::buffa::OwnedView<TransactionView<'static>>>
for TransactionOwnedView {
    fn from(inner: ::buffa::OwnedView<TransactionView<'static>>) -> Self {
        TransactionOwnedView(inner)
    }
}
impl ::core::convert::From<TransactionOwnedView>
for ::buffa::OwnedView<TransactionView<'static>> {
    fn from(wrapper: TransactionOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<TransactionView<'static>>>
for TransactionOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<TransactionView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Transaction {
    type View<'a> = TransactionView<'a>;
    type ViewHandle = TransactionOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct VinView<'a> {
    /// The transaction id
    ///
    /// Field 1: `txid`
    pub txid: &'a str,
    /// The output number
    ///
    /// Field 2: `vout`
    pub vout: u32,
    /// The script
    ///
    /// Field 3: `script_sig`
    pub script_sig: ::buffa::MessageFieldView<
        super::super::__buffa::view::ScriptSigView<'a>,
    >,
    /// The script sequence number
    ///
    /// Field 4: `sequence`
    pub sequence: u32,
    /// hex-encoded witness data (if any)
    ///
    /// Field 5: `txinwitness`
    pub txinwitness: ::buffa::RepeatedView<'a, &'a str>,
    /// hex-encoded coinbase
    ///
    /// Field 6: `coinbase`
    pub coinbase: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for VinView<'a> {
    type Owned = super::super::Vin;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.txid = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.vout = ::buffa::types::decode_uint32(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.script_sig.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.script_sig = ::buffa::MessageFieldView::set(
                            <super::super::__buffa::view::ScriptSigView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.sequence = ::buffa::types::decode_uint32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.coinbase = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::borrow_str(&mut cur)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                view.txinwitness.push(__elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Vin, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Vin, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Vin {
            txid: self.txid.to_string(),
            vout: self.vout,
            script_sig: match self.script_sig.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        super::super::ScriptSig,
                        ::buffa::Inline<super::super::ScriptSig>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            sequence: self.sequence,
            txinwitness: self.txinwitness.iter().map(|s| s.to_string()).collect(),
            coinbase: self.coinbase.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for VinView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.txid.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.txid) as u64;
        }
        if self.vout != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.vout) as u64;
        }
        if self.script_sig.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.script_sig.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.sequence != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.sequence) as u64;
        }
        for v in &self.txinwitness {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if !self.coinbase.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.coinbase) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.txid.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.txid, buf);
        }
        if self.vout != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.vout, buf);
        }
        if self.script_sig.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.script_sig.write_to(__cache, buf);
        }
        if self.sequence != 0u32 {
            ::buffa::types::put_uint32_field(4u32, self.sequence, buf);
        }
        for v in &self.txinwitness {
            ::buffa::types::put_string_field(5u32, v, buf);
        }
        if !self.coinbase.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.coinbase, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for VinView<'a> {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Vin";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Vin";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Vin";
}
::buffa::impl_default_view_instance!(VinView);
::buffa::impl_view_reborrow!(VinView);
/** Self-contained, `'static` owned view of a `Vin` message.

 Wraps [`::buffa::OwnedView`]`<`[`VinView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`VinView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct VinOwnedView(::buffa::OwnedView<VinView<'static>>);
impl VinOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(VinOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            VinOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Vin,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(VinOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`VinView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &VinView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Vin {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The transaction id
    ///
    /// Field 1: `txid`
    #[must_use]
    pub fn txid(&self) -> &'_ str {
        self.0.reborrow().txid
    }
    /// The output number
    ///
    /// Field 2: `vout`
    #[must_use]
    pub fn vout(&self) -> u32 {
        self.0.reborrow().vout
    }
    /// The script
    ///
    /// Field 3: `script_sig`
    #[must_use]
    pub fn script_sig(
        &self,
    ) -> &::buffa::MessageFieldView<super::super::__buffa::view::ScriptSigView<'_>> {
        &self.0.reborrow().script_sig
    }
    /// The script sequence number
    ///
    /// Field 4: `sequence`
    #[must_use]
    pub fn sequence(&self) -> u32 {
        self.0.reborrow().sequence
    }
    /// hex-encoded witness data (if any)
    ///
    /// Field 5: `txinwitness`
    #[must_use]
    pub fn txinwitness(&self) -> &::buffa::RepeatedView<'_, &'_ str> {
        &self.0.reborrow().txinwitness
    }
    /// hex-encoded coinbase
    ///
    /// Field 6: `coinbase`
    #[must_use]
    pub fn coinbase(&self) -> &'_ str {
        self.0.reborrow().coinbase
    }
}
impl ::core::convert::From<::buffa::OwnedView<VinView<'static>>> for VinOwnedView {
    fn from(inner: ::buffa::OwnedView<VinView<'static>>) -> Self {
        VinOwnedView(inner)
    }
}
impl ::core::convert::From<VinOwnedView> for ::buffa::OwnedView<VinView<'static>> {
    fn from(wrapper: VinOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<VinView<'static>>> for VinOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<VinView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Vin {
    type View<'a> = VinView<'a>;
    type ViewHandle = VinOwnedView;
}
#[derive(Clone, Debug, Default)]
#[allow(non_snake_case)]
pub struct VoutView<'a> {
    /// The value in BTC
    ///
    /// Field 1: `value`
    pub value: f64,
    /// index
    ///
    /// Field 2: `n`
    pub n: u32,
    /// Field 3: `script_pubKey`
    pub script_pubKey: ::buffa::MessageFieldView<
        super::super::__buffa::view::ScriptPubKeyView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for VoutView<'a> {
    type Owned = super::super::Vout;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Fixed64,
                )?;
                view.value = ::buffa::types::decode_double(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.n = ::buffa::types::decode_uint32(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.script_pubKey.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.script_pubKey = ::buffa::MessageFieldView::set(
                            <super::super::__buffa::view::ScriptPubKeyView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Vout, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Vout, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Vout {
            value: self.value,
            n: self.n,
            script_pubKey: match self.script_pubKey.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        super::super::ScriptPubKey,
                        ::buffa::Inline<super::super::ScriptPubKey>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for VoutView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.value.to_bits() != 0u64 {
            size += 1u64 + ::buffa::types::FIXED64_ENCODED_LEN as u64;
        }
        if self.n != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.n) as u64;
        }
        if self.script_pubKey.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.script_pubKey.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.value.to_bits() != 0u64 {
            ::buffa::types::put_double_field(1u32, self.value, buf);
        }
        if self.n != 0u32 {
            ::buffa::types::put_uint32_field(2u32, self.n, buf);
        }
        if self.script_pubKey.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.script_pubKey.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for VoutView<'a> {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "Vout";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.Vout";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.Vout";
}
::buffa::impl_default_view_instance!(VoutView);
::buffa::impl_view_reborrow!(VoutView);
/** Self-contained, `'static` owned view of a `Vout` message.

 Wraps [`::buffa::OwnedView`]`<`[`VoutView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`VoutView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct VoutOwnedView(::buffa::OwnedView<VoutView<'static>>);
#[allow(non_snake_case)]
impl VoutOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(VoutOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            VoutOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Vout,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(VoutOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`VoutView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &VoutView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Vout {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The value in BTC
    ///
    /// Field 1: `value`
    #[must_use]
    pub fn value(&self) -> f64 {
        self.0.reborrow().value
    }
    /// index
    ///
    /// Field 2: `n`
    #[must_use]
    pub fn n(&self) -> u32 {
        self.0.reborrow().n
    }
    /// Field 3: `script_pubKey`
    #[must_use]
    pub fn script_pubKey(
        &self,
    ) -> &::buffa::MessageFieldView<super::super::__buffa::view::ScriptPubKeyView<'_>> {
        &self.0.reborrow().script_pubKey
    }
}
impl ::core::convert::From<::buffa::OwnedView<VoutView<'static>>> for VoutOwnedView {
    fn from(inner: ::buffa::OwnedView<VoutView<'static>>) -> Self {
        VoutOwnedView(inner)
    }
}
impl ::core::convert::From<VoutOwnedView> for ::buffa::OwnedView<VoutView<'static>> {
    fn from(wrapper: VoutOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<VoutView<'static>>> for VoutOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<VoutView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Vout {
    type View<'a> = VoutView<'a>;
    type ViewHandle = VoutOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct ScriptSigView<'a> {
    /// The asm
    ///
    /// Field 1: `asm`
    pub asm: &'a str,
    /// The hex
    ///
    /// Field 2: `hex`
    pub hex: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for ScriptSigView<'a> {
    type Owned = super::super::ScriptSig;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.asm = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hex = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::ScriptSig, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::ScriptSig, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ScriptSig {
            asm: self.asm.to_string(),
            hex: self.hex.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ScriptSigView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.asm.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.asm) as u64;
        }
        if !self.hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hex) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.asm.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.asm, buf);
        }
        if !self.hex.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.hex, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for ScriptSigView<'a> {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "ScriptSig";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.ScriptSig";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.ScriptSig";
}
::buffa::impl_default_view_instance!(ScriptSigView);
::buffa::impl_view_reborrow!(ScriptSigView);
/** Self-contained, `'static` owned view of a `ScriptSig` message.

 Wraps [`::buffa::OwnedView`]`<`[`ScriptSigView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ScriptSigView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ScriptSigOwnedView(::buffa::OwnedView<ScriptSigView<'static>>);
impl ScriptSigOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ScriptSigOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ScriptSigOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ScriptSig,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ScriptSigOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ScriptSigView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ScriptSigView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::ScriptSig {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// The asm
    ///
    /// Field 1: `asm`
    #[must_use]
    pub fn asm(&self) -> &'_ str {
        self.0.reborrow().asm
    }
    /// The hex
    ///
    /// Field 2: `hex`
    #[must_use]
    pub fn hex(&self) -> &'_ str {
        self.0.reborrow().hex
    }
}
impl ::core::convert::From<::buffa::OwnedView<ScriptSigView<'static>>>
for ScriptSigOwnedView {
    fn from(inner: ::buffa::OwnedView<ScriptSigView<'static>>) -> Self {
        ScriptSigOwnedView(inner)
    }
}
impl ::core::convert::From<ScriptSigOwnedView>
for ::buffa::OwnedView<ScriptSigView<'static>> {
    fn from(wrapper: ScriptSigOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ScriptSigView<'static>>>
for ScriptSigOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ScriptSigView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ScriptSig {
    type View<'a> = ScriptSigView<'a>;
    type ViewHandle = ScriptSigOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct ScriptPubKeyView<'a> {
    /// the asm
    ///
    /// Field 1: `asm`
    pub asm: &'a str,
    /// the hex
    ///
    /// Field 2: `hex`
    pub hex: &'a str,
    /// The required sigs
    ///
    /// Field 3: `req_sigs`
    pub req_sigs: i32,
    /// The type, eg 'pubkeyhash'
    ///
    /// Field 4: `type`
    pub r#type: &'a str,
    /// bitcoin address
    ///
    /// Field 5: `address`
    pub address: &'a str,
    /// bitcoin addresses (deprecated, empty when 'address' is set)
    ///
    /// Field 6: `addresses`
    pub addresses: ::buffa::RepeatedView<'a, &'a str>,
}
impl<'a> ::buffa::MessageView<'a> for ScriptPubKeyView<'a> {
    type Owned = super::super::ScriptPubKey;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.asm = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hex = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.req_sigs = ::buffa::types::decode_int32(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.r#type = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.address = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::borrow_str(&mut cur)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                view.addresses.push(__elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::ScriptPubKey, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::ScriptPubKey, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ScriptPubKey {
            asm: self.asm.to_string(),
            hex: self.hex.to_string(),
            req_sigs: self.req_sigs,
            r#type: self.r#type.to_string(),
            address: self.address.to_string(),
            addresses: self.addresses.iter().map(|s| s.to_string()).collect(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ScriptPubKeyView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.asm.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.asm) as u64;
        }
        if !self.hex.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.hex) as u64;
        }
        if self.req_sigs != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.req_sigs) as u64;
        }
        if !self.r#type.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.r#type) as u64;
        }
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.address) as u64;
        }
        for v in &self.addresses {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.asm.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.asm, buf);
        }
        if !self.hex.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.hex, buf);
        }
        if self.req_sigs != 0i32 {
            ::buffa::types::put_int32_field(3u32, self.req_sigs, buf);
        }
        if !self.r#type.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.r#type, buf);
        }
        if !self.address.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.address, buf);
        }
        for v in &self.addresses {
            ::buffa::types::put_string_field(6u32, v, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for ScriptPubKeyView<'a> {
    const PACKAGE: &'static str = "sf.bitcoin.type.v1";
    const NAME: &'static str = "ScriptPubKey";
    const FULL_NAME: &'static str = "sf.bitcoin.type.v1.ScriptPubKey";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.bitcoin.type.v1.ScriptPubKey";
}
::buffa::impl_default_view_instance!(ScriptPubKeyView);
::buffa::impl_view_reborrow!(ScriptPubKeyView);
/** Self-contained, `'static` owned view of a `ScriptPubKey` message.

 Wraps [`::buffa::OwnedView`]`<`[`ScriptPubKeyView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ScriptPubKeyView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ScriptPubKeyOwnedView(::buffa::OwnedView<ScriptPubKeyView<'static>>);
impl ScriptPubKeyOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ScriptPubKeyOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ScriptPubKeyOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ScriptPubKey,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ScriptPubKeyOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ScriptPubKeyView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ScriptPubKeyView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::ScriptPubKey {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// the asm
    ///
    /// Field 1: `asm`
    #[must_use]
    pub fn asm(&self) -> &'_ str {
        self.0.reborrow().asm
    }
    /// the hex
    ///
    /// Field 2: `hex`
    #[must_use]
    pub fn hex(&self) -> &'_ str {
        self.0.reborrow().hex
    }
    /// The required sigs
    ///
    /// Field 3: `req_sigs`
    #[must_use]
    pub fn req_sigs(&self) -> i32 {
        self.0.reborrow().req_sigs
    }
    /// The type, eg 'pubkeyhash'
    ///
    /// Field 4: `type`
    #[must_use]
    pub fn r#type(&self) -> &'_ str {
        self.0.reborrow().r#type
    }
    /// bitcoin address
    ///
    /// Field 5: `address`
    #[must_use]
    pub fn address(&self) -> &'_ str {
        self.0.reborrow().address
    }
    /// bitcoin addresses (deprecated, empty when 'address' is set)
    ///
    /// Field 6: `addresses`
    #[must_use]
    pub fn addresses(&self) -> &::buffa::RepeatedView<'_, &'_ str> {
        &self.0.reborrow().addresses
    }
}
impl ::core::convert::From<::buffa::OwnedView<ScriptPubKeyView<'static>>>
for ScriptPubKeyOwnedView {
    fn from(inner: ::buffa::OwnedView<ScriptPubKeyView<'static>>) -> Self {
        ScriptPubKeyOwnedView(inner)
    }
}
impl ::core::convert::From<ScriptPubKeyOwnedView>
for ::buffa::OwnedView<ScriptPubKeyView<'static>> {
    fn from(wrapper: ScriptPubKeyOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ScriptPubKeyView<'static>>>
for ScriptPubKeyOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ScriptPubKeyView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ScriptPubKey {
    type View<'a> = ScriptPubKeyView<'a>;
    type ViewHandle = ScriptPubKeyOwnedView;
}
